export const OrderActionTypes = {
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
  RESET_CREATED_ORDER: 'RESET_CREATED_ORDER',

  GET_ORDER_DETAILS_START: 'GET_ORDER_DETAILS_START',
  GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS',
  GET_ORDER_DETAILS_FAILURE: 'GET_ORDER_DETAILS_FAILURE',

  GET_USER_ORDERS_START: 'GET_USER_ORDERS_START',
  GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
  GET_USER_ORDERS_FAILURE: 'GET_USER_ORDERS_FAILURE',

  PAY_ORDER_START: 'PAY_ORDER_START',
  PAY_ORDER_SUCCESS: 'PAY_ORDER_SUCCESS',
  PAY_ORDER_FAILURE: 'PAY_ORDER_FAILURE',
  PAY_ORDER_RESET: 'PAY_ORDER_RESET',

  UPDATE_ORDER_TO_DELIVERED_START: 'UPDATE_ORDER_TO_DELIVERED_START',
  UPDATE_ORDER_TO_DELIVERED_SUCCESS: 'UPDATE_ORDER_TO_DELIVERED_SUCCESS',
  UPDATE_ORDER_TO_DELIVERED_FAILURE: 'UPDATE_ORDER_TO_DELIVERED_FAILURE',
  UPDATE_ORDER_TO_DELIVERED_RESET: 'UPDATE_ORDER_TO_DELIVERED_RESET',

  GET_ALL_ORDERS_START: 'GET_ALL_ORDERS_START',
  GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
  GET_ALL_ORDERS_FAILURE: 'GET_ALL_ORDERS_FAILURE',
}
