export const OrderActionTypes = {
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

  GET_ORDER_DETAILS_START: 'GET_ORDER_DETAILS_START',
  GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS',
  GET_ORDER_DETAILS_FAILURE: 'GET_ORDER_DETAILS_FAILURE',

  GET_USER_ORDERS_START: 'GET_USER_ORDERS_START',
  GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
  GET_USER_ORDERS_FAILURE: 'GET_USER_ORDERS_FAILURE',

  PAY_ORDER_START: 'PAY_ORDER_START',
  PAY_ORDER_SUCCESS: 'PAY_ORDER_SUCCESS',
  PAY_ORDER_FAILURE: 'PAY_ORDER_FAILURE',
  PAY_ORDER_RESET: 'PAY_ORDER_RESET',
}
