export const UserActionTypes = {
  USER_SIGNIN_START: 'USER_SIGNIN_START',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',

  USER_SIGNUP_START: 'USER_SIGNUP_START',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  GET_USER_DETAILS_START: 'GET_USER_DETAILS_START',
  GET_USER_DETAILS_SUCCESS: 'GET_USER_DETAILS_SUCCESS',
  GET_USER_DETAILS_FAILURE: 'GET_USER_DETAILS_FAILURE',
  RESET_USER_DETAILS: 'RESET_USER_DETAILS',

  UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',
}
